### ISSUE TITLE
Adjusting new SQL queries for selected filtered date

### ISSUE THREAD

**Issue by tunix** [monitise-mea/gerrit-dashboard-server#18]
Currently _Average Merge Duration by Project_ and _Average First Review Duration By Project_ are calculated by excluding date intervals. Is it possible to include date filtering into the SQL query so that we can see the change over time?

Currently we have filters for:
- TODAY
- THIS WEEK
- THIS MONTH
- LAST 30 DAYS
- LAST 6 MONTHS

which correspond to certain dates and then injected into SQL queries. This feature will be very usefull especially if we develop project pages.

**Comment by mustafaersahin** [comment]
Standard filtering mechanism is applied to both statistics in new pull request.
